name: Deploy Codeberg Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Deploy to pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: pages
          publish_dir: ./out
          github_token: ${{ secrets.CODEBERG_TOKEN || secrets.GITHUB_TOKEN }}
